services:
    localstack:
      image: localstack/localstack:4.14
      container_name: localstack
      environment:
        SERVICES: s3
        DEFAULT_REGION: ${REGION}
      volumes:
        - localstack_vol:/var/lib/localstack
      ports:
        - "4566:4566"

    pgdatabase:
      image: postgres:17
      container_name: pgdatabase
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - lakehouse_vol:/var/lib/postgresql/data
      ports:
        - "5433:5432"

    pipeline:
      container_name: lakehouse_pipeline
      build: .
      env_file:
        - .env
      depends_on:
        - localstack
        - pgdatabase

volumes:
  localstack_vol:
  lakehouse_vol: